spring.application.name=iw3
# ===================================================================
# Configuración de Base de Datos MySQL
# ===================================================================
dev.info.enabled=true
spring.datasource.url=jdbc:mysql://localhost:3306/iw3_db?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true

